import { Hono, type Context } from 'hono';
import { Env, all, one, run, insert, update, code, fail, requireRoles } from './shared';

type C = Context<Env>;
type Data = Record<string, any>;
async function body(c:C):Promise<Data> {const d=await c.req.json();if(!d||Array.isArray(d)||typeof d!=='object')throw fail(422,'Expected a JSON object');return d;}
const today = () => new Date().toISOString().slice(0, 10);
const round = (n: number, digits = 2) => Number(n.toFixed(digits));
function text(d: Data, k: string, fallback?: string) { const v=d[k] ?? fallback; if(typeof v !== 'string' || !v.trim()) throw fail(422, `${k} is required`); return v.trim(); }
function num(d: Data,k:string,fallback?:number,positive=false) { const v=d[k] ?? fallback; if(typeof v!=='number'||!Number.isFinite(v)||v<0||(positive&&v===0)) throw fail(422,`${k} must be ${positive?'positive':'nonnegative'}`); return v; }
function date(d:Data,k:string) { const v=d[k]??today(); if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v) throw fail(422,`${k} must be a valid date`); return v; }
function id(d:Data,k:string) {const v=num(d,k,undefined,true); if(!Number.isInteger(v))throw fail(422,`${k} must be an integer`); return v;}
function bool(d:Data,k:string,fallback=false) {const v=d[k]??fallback;if(typeof v!=='boolean')throw fail(422,`${k} must be boolean`);return v;}
async function exists(c:C,table:string,value:number,label=table) { const row=await one(c,`SELECT * FROM ${table} WHERE id=?`,value); if(!row)throw fail(404,`${label} not found`);return row as Data; }
function add(c:C,table:string,data:Data) { const keys=Object.keys(data);return c.env.DB.prepare(`INSERT INTO ${table} (${keys.join(',')}) VALUES (${keys.map(()=>'?').join(',')}) RETURNING *`).bind(...Object.values(data).map(v=>typeof v==='boolean'?Number(v):v)); }
async function sum(c:C,sql:string,...args:any[]) {return Number((await one(c,sql,...args) as Data)?.n??0);}
async function refs(c:C,d:Data) {for(const [key,table] of [['job_id','jobs'],['platform_id','platforms'],['machine_id','machines']] )if(d[key]!=null)await exists(c,table,id(d,key));}
async function pnl(c:C,requested?:string) {
 const period=requested??today().slice(0,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(period))throw fail(422,'period must be YYYY-MM');
 const start=period+'-01',end=new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5,7)),1)).toISOString().slice(0,10);
 const ranged=(table:string,field:string,value:string,extra='')=>sum(c,`SELECT COALESCE(SUM(${value}),0) n FROM ${table} WHERE ${field}>=? AND ${field}<? ${extra}`,start,end);
 const [sales,material,direct,overhead,payroll,weight,reshoot]=await Promise.all([ranged('invoices','invoice_date','subtotal'),ranged('inventory_transactions','txn_date','value',"AND txn_type IN ('CONSUMPTION','WASTAGE')"),ranged('expenses','expense_date','amount','AND is_direct_cost=1 AND approved=1'),ranged('expenses','expense_date','amount','AND is_direct_cost=0 AND approved=1'),sum(c,'SELECT COALESCE(SUM(net_payable),0) n FROM payroll WHERE period=?',period),ranged('jobs','weight_recorded_at','billable_weight_g'),ranged('print_attempts','started_at','estimated_cost','AND is_reshoot=1')]);
 const cost=material+direct+reshoot;return {period,net_sales:round(sales),material_consumed:round(material),other_direct_cost:round(direct),reshoot_cost:round(reshoot),direct_production_cost:round(cost),successful_billable_weight_g:round(weight,3),cost_per_gram:weight?round(cost/weight):0,gross_profit:round(sales-cost),company_overhead:round(overhead+payroll),net_operating_profit:round(sales-cost-overhead-payroll)};
}
async function cash(c:C) {const [invoiced,paid,purchases,supplier]=await Promise.all([sum(c,'SELECT COALESCE(SUM(total_amount),0) n FROM invoices'),sum(c,'SELECT COALESCE(SUM(amount),0) n FROM payments'),sum(c,'SELECT COALESCE(SUM(quantity*rate+tax_amount),0) n FROM purchases'),sum(c,'SELECT COALESCE(SUM(paid_amount),0) n FROM purchases')]);return {customer_outstanding:round(Math.max(invoiced-paid,0)),supplier_payable:round(Math.max(purchases-supplier,0))};}
async function materials(c:C) {return all(c,`SELECT m.*,ROUND(COALESCE(SUM(CASE WHEN t.txn_type='PURCHASE' THEN t.quantity WHEN t.txn_type IN ('CONSUMPTION','WASTAGE') THEN -t.quantity ELSE 0 END),0),3) stock FROM materials m LEFT JOIN inventory_transactions t ON t.material_id=m.id GROUP BY m.id ORDER BY m.name`);}

export function registerFinance(app:Hono<Env>) {
 app.get('/api/customers',async c=>c.json(await all(c,'SELECT id,code,name,email,whatsapp,default_rate,credit_days FROM customers ORDER BY name')));
 app.post('/api/customers',async c=>{const d=await body(c);const row=await insert(c,'customers',{code:code('CUST'),name:text(d,'name'),email:d.email??null,whatsapp:d.whatsapp??null,gst_number:d.gst_number??null,default_rate:num(d,'default_rate',0),credit_days:num(d,'credit_days',0)});return c.json(row);});
 for(const [path,table,fields,defaults,numeric] of [
 ['materials','materials',['code','name','unit','minimum_stock'],{unit:'kg',minimum_stock:0},['minimum_stock']],
 ['suppliers','suppliers',['code','name','gst_number','contact'],{},[]],
 ['employees','employees',['code','name','department','role','monthly_salary'],{department:'Production',role:'Operator',monthly_salary:0},['monthly_salary']],
 ] as [string,string,string[],Data,string[]][]) {
   if(path!=='materials')app.get('/api/'+path,async c=>c.json(await all(c,`SELECT * FROM ${table} ORDER BY name`)));
   app.post('/api/'+path,async c=>{const d=await body(c);const values:Data={};for(const k of fields)values[k]=numeric.includes(k)?num(d,k,defaults[k]):['code','name'].includes(k)?text(d,k):d[k]??defaults[k]??null;return c.json(await insert(c,table,values));});
 }
 app.get('/api/materials',async c=>c.json(await materials(c)));
 app.post('/api/purchases',async c=>{const d=await body(c);const supplier_id=id(d,'supplier_id'),material_id=id(d,'material_id');await exists(c,'suppliers',supplier_id);await exists(c,'materials',material_id);const quantity=num(d,'quantity',undefined,true),rate=num(d,'rate'),purchase_date=date(d,'purchase_date');const results=await c.env.DB.batch([add(c,'purchases',{supplier_id,material_id,purchase_date,quantity,rate,tax_amount:num(d,'tax_amount',0),paid_amount:num(d,'paid_amount',0),invoice_no:d.invoice_no??null}),add(c,'inventory_transactions',{material_id,txn_date:purchase_date,txn_type:'PURCHASE',quantity,unit_cost:rate,value:quantity*rate,notes:`Purchase ${d.invoice_no??'received'}`})]);const row=results[0].results[0] as Data;return c.json({id:row.id,inventory_added:quantity,purchase_value:round(quantity*rate)});});
 app.post('/api/inventory/consume',async c=>{const d=await body(c);const material_id=id(d,'material_id');await exists(c,'materials',material_id);await refs(c,d);const quantity=num(d,'quantity',undefined,true),unit_cost=num(d,'unit_cost');const row=await insert(c,'inventory_transactions',{material_id,txn_date:date(d,'txn_date'),txn_type:'CONSUMPTION',quantity,unit_cost,value:quantity*unit_cost,job_id:d.job_id??null,platform_id:d.platform_id??null,machine_id:d.machine_id??null,notes:d.notes??null});return c.json({id:row.id,production_cost_added:round(quantity*unit_cost)});});
 app.get('/api/expenses',async c=>{requireRoles(c,'ADMIN');return c.json(await all(c,'SELECT id,expense_date date,category,subcategory,description,amount,is_direct_cost,related_type,related_id,approved FROM expenses ORDER BY expense_date DESC,id DESC'));});
 app.post('/api/expenses',async c=>{requireRoles(c,'ADMIN','ACCOUNTS','STAFF','OPERATOR');const d=await body(c);const row=await insert(c,'expenses',{expense_date:date(d,'expense_date'),category:text(d,'category'),subcategory:d.subcategory??null,description:text(d,'description'),amount:num(d,'amount',undefined,true),tax_amount:num(d,'tax_amount',0),is_direct_cost:bool(d,'is_direct_cost'),related_type:d.related_type??'GENERAL',related_id:d.related_id??null,payment_mode:d.payment_mode??'BANK',approved:c.get('user').role==='ADMIN'});return c.json({id:row.id,amount:row.amount,approved:!!row.approved});});
 app.post('/api/expenses/:id/approve',async c=>{requireRoles(c,'ADMIN');const eid=Number(c.req.param('id'));await exists(c,'expenses',eid);await update(c,'expenses',eid,{approved:true});return c.json({ok:true,id:eid});});
 app.get('/api/payroll',async c=>{requireRoles(c,'ADMIN');return c.json(await all(c,'SELECT p.*,e.name employee_name FROM payroll p JOIN employees e ON e.id=p.employee_id ORDER BY p.id DESC'));});
 app.post('/api/payroll',async c=>{requireRoles(c,'ADMIN');const d=await body(c);const employee_id=id(d,'employee_id');await exists(c,'employees',employee_id);const period=text(d,'period');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(period))throw fail(422,'period must be YYYY-MM');const data:Data={employee_id,period,paid:bool(d,'paid')};for(const k of ['basic','bonus','commission','reimbursement','advance_deduction','other_deduction'])data[k]=num(d,k,k==='basic'?undefined:0);data.net_payable=data.basic+data.bonus+data.commission+data.reimbursement-data.advance_deduction-data.other_deduction;const row=await insert(c,'payroll',data);return c.json({id:row.id,net_payable:round(data.net_payable)});});
 app.get('/api/advances',async c=>{requireRoles(c,'ADMIN');return c.json(await all(c,'SELECT a.*,e.name employee_name,j.number job_number FROM employee_advances a JOIN employees e ON e.id=a.employee_id LEFT JOIN jobs j ON j.id=a.job_id ORDER BY advance_date DESC,a.id DESC'));});
 app.post('/api/advances',async c=>{requireRoles(c,'ADMIN');const d=await body(c);const employee_id=id(d,'employee_id');const employee=await exists(c,'employees',employee_id);await refs(c,d);const row=await insert(c,'employee_advances',{employee_id,job_id:d.job_id??null,advance_date:date(d,'advance_date'),amount:num(d,'amount',undefined,true),purpose:text(d,'purpose','Salary advance'),period:d.period??null,notes:d.notes??null,status:'OPEN'});return c.json({id:row.id,employee:employee.name,amount:round(row.amount),status:row.status});});
 app.get('/api/travel',async c=>{requireRoles(c,'ADMIN');const rows=await all(c,'SELECT t.*,e.name employee_name,j.number job_number FROM travel_advances t JOIN employees e ON e.id=t.employee_id LEFT JOIN jobs j ON j.id=t.job_id ORDER BY trip_date DESC,t.id DESC');return c.json(rows.map((t:Data)=>{const total=['flight_amount','hotel_amount','taxi_amount','porter_amount','other_amount'].reduce((n,k)=>n+t[k],0);return {...t,total_expense:round(total),balance:round(t.advance_amount+t.settled_amount-total)};}));});
 app.post('/api/travel',async c=>{requireRoles(c,'ADMIN');const d=await body(c);const employee_id=id(d,'employee_id');await exists(c,'employees',employee_id);await refs(c,d);const data:Data={employee_id,job_id:d.job_id??null,trip_date:date(d,'trip_date'),destination:text(d,'destination'),purpose:text(d,'purpose'),notes:d.notes??null};for(const k of ['advance_amount','flight_amount','hotel_amount','taxi_amount','porter_amount','other_amount','settled_amount'])data[k]=num(d,k,0);const expense=['flight_amount','hotel_amount','taxi_amount','porter_amount','other_amount'].reduce((n,k)=>n+data[k],0),balance=data.advance_amount+data.settled_amount-expense;data.status=Math.abs(balance)<0.01?'SETTLED':'OPEN';const statements=[add(c,'travel_advances',data)];if(expense)statements.push(add(c,'expenses',{expense_date:data.trip_date,category:'Travel',subcategory:'Trip Settlement',description:`${data.destination} - ${data.purpose}`,amount:expense,is_direct_cost:!!data.job_id,related_type:data.job_id?'JOB':'EMPLOYEE',related_id:data.job_id??employee_id,payment_mode:'BANK',approved:true}));const results=await c.env.DB.batch(statements);const row=results[0].results[0] as Data;return c.json({id:row.id,status:data.status,total_expense:round(expense),balance:round(balance)});});
 app.post('/api/invoices/from-job',async c=>{requireRoles(c,'ADMIN','ACCOUNTS');const d=await body(c);const job=await exists(c,'jobs',id(d,'job_id'));const customer=await exists(c,'customers',job.customer_id);const amount=job.billable_weight_g*customer.default_rate,extra=num(d,'extra_charge',0),subtotal=amount+extra,tax=subtotal*num(d,'tax_rate',0)/100;const number=code('INV');const statements=[add(c,'invoices',{number,customer_id:job.customer_id,invoice_date:today(),subtotal,tax_amount:tax,total_amount:subtotal+tax,status:'SENT'}),c.env.DB.prepare('INSERT INTO invoice_lines(invoice_id,job_id,description,weight_g,rate,amount) SELECT id,?,?,?,?,? FROM invoices WHERE number=?').bind(job.id,`Wax printing ${job.number}`,job.billable_weight_g,customer.default_rate,amount,number)];if(extra)statements.push(c.env.DB.prepare('INSERT INTO invoice_lines(invoice_id,job_id,description,weight_g,rate,amount) SELECT id,?,?,0,0,? FROM invoices WHERE number=?').bind(job.id,text(d,'extra_description','Other Charges'),extra,number));statements.push(c.env.DB.prepare("UPDATE jobs SET status='INVOICED' WHERE id=?").bind(job.id));const results=await c.env.DB.batch(statements);const inv=results[0].results[0] as Data;return c.json({id:inv.id,number:inv.number,subtotal:round(subtotal),tax:round(tax),total:round(subtotal+tax)});});
 app.get('/api/invoices',async c=>{requireRoles(c,'ADMIN','ACCOUNTS');return c.json(await all(c,'SELECT i.id,i.number,i.customer_id,i.invoice_date date,i.subtotal,i.tax_amount tax,i.total_amount total,COALESCE(SUM(p.amount),0) paid,MAX(i.total_amount-COALESCE(SUM(p.amount),0),0) outstanding,i.status FROM invoices i LEFT JOIN payments p ON p.invoice_id=i.id GROUP BY i.id ORDER BY i.id DESC'));});
 app.post('/api/payments',async c=>{requireRoles(c,'ADMIN','ACCOUNTS');const d=await body(c);const inv=await exists(c,'invoices',id(d,'invoice_id'));const results=await c.env.DB.batch([add(c,'payments',{invoice_id:inv.id,payment_date:date(d,'payment_date'),amount:num(d,'amount',undefined,true),payment_mode:d.payment_mode??'BANK',reference:d.reference??null}),c.env.DB.prepare("UPDATE invoices SET status=CASE WHEN (SELECT COALESCE(SUM(amount),0) FROM payments WHERE invoice_id=?)>=total_amount THEN 'PAID' ELSE 'PART_PAID' END WHERE id=?").bind(inv.id,inv.id)]);const row=results[0].results[0] as Data;const paid=await sum(c,'SELECT SUM(amount) n FROM payments WHERE invoice_id=?',inv.id);return c.json({id:row.id,invoice:inv.number,paid_total:round(paid),outstanding:round(Math.max(inv.total_amount-paid,0))});});
 app.get('/api/reports/pnl',async c=>{requireRoles(c,'ADMIN');return c.json(await pnl(c,c.req.query('period')));});
 app.get('/api/reports/job-profitability',async c=>{requireRoles(c,'ADMIN');const rows=await all(c,`SELECT j.number job,c.name customer,j.billable_weight_g weight_g,COALESCE((SELECT SUM(amount) FROM invoice_lines WHERE job_id=j.id),0) revenue,COALESCE((SELECT SUM(value) FROM inventory_transactions WHERE job_id=j.id AND txn_type IN ('CONSUMPTION','WASTAGE')),0)+COALESCE((SELECT SUM(amount) FROM expenses WHERE related_type='JOB' AND related_id=j.id AND is_direct_cost=1 AND approved=1),0)+COALESCE((SELECT SUM(a.estimated_cost) FROM print_attempts a JOIN job_files f ON f.id=a.job_file_id WHERE f.job_id=j.id AND a.is_reshoot=1),0) direct_cost FROM jobs j JOIN customers c ON c.id=j.customer_id ORDER BY j.id DESC`);return c.json(rows.map((r:Data)=>({...r,revenue:round(r.revenue),direct_cost:round(r.direct_cost),gross_profit:round(r.revenue-r.direct_cost),margin_pct:r.revenue?round((r.revenue-r.direct_cost)/r.revenue*100):0})));});
 app.get('/api/dashboard',async c=>{requireRoles(c,'ADMIN');const [jobs,reshoots,printing,qc,p,cashInfo,stock]=await Promise.all([sum(c,'SELECT COUNT(*) n FROM jobs'),sum(c,"SELECT COUNT(*) n FROM reshoot_tickets WHERE status='OPEN'"),sum(c,"SELECT COUNT(*) n FROM print_attempts WHERE status='PRINTING'"),sum(c,"SELECT COUNT(*) n FROM print_attempts WHERE status='QC_FAILED'"),pnl(c),cash(c),materials(c)]);return c.json({counts:{jobs,open_reshoots:reshoots,printing,qc_failed:qc},pnl:p,cash:cashInfo,low_stock:stock.filter((r:Data)=>r.stock<=r.minimum_stock).map((r:Data)=>({material:r.name,qty:r.stock,minimum:r.minimum_stock}))});});
 registerGmail(app);
}

async function gmailStatus(c:C) {const settings=await one(c,"SELECT value FROM integration_settings WHERE key='gmail'") as Data|null;const d=settings?JSON.parse(settings.value):{};const env=c.env as any;return {enabled:d.enabled??false,configured:!!(env.GMAIL_CLIENT_ID&&env.GMAIL_CLIENT_SECRET&&env.GMAIL_REFRESH_TOKEN),mode:'oauth',user:d.user??'',mailbox:d.mailbox??'INBOX',fetch_query:d.fetch_query??'is:unread',fetch_limit:d.fetch_limit??25,pubsub_topic:env.GMAIL_PUBSUB_TOPIC??null,archive_label:null};}
async function gmailToken(c:C) {const current=await gmailStatus(c);if(!current.enabled)throw fail(400,'Gmail integration is disabled');if(!current.configured)throw fail(400,'Set GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET and GMAIL_REFRESH_TOKEN as Worker secrets to connect Gmail');const e=c.env as any;const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:new URLSearchParams({client_id:e.GMAIL_CLIENT_ID,client_secret:e.GMAIL_CLIENT_SECRET,refresh_token:e.GMAIL_REFRESH_TOKEN,grant_type:'refresh_token'})});const data=await response.json() as Data;if(!response.ok||!data.access_token)throw fail(502,'Google rejected the configured OAuth credentials');return data.access_token;}
async function gmailFetch(c:C,path:string,token:string) {const response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/'+path,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw fail(502,`Gmail API returned ${response.status}`);return await response.json() as Data;}
function registerGmail(app:Hono<Env>) {
 app.get('/api/integrations/gmail/status',async c=>c.json(await gmailStatus(c)));
 app.get('/api/settings/integrations',async c=>{requireRoles(c,'ADMIN');return c.json({gmail:await gmailStatus(c),magics:{agent_token_configured:!!(c.env as any).AGENT_TOKEN,workstation_default:'MAGICS-PC-01',local_agent_folder:'magics_agent',queue_endpoint:'/api/magics/agent/jobs'}});});
 app.post('/api/settings/gmail',async c=>{requireRoles(c,'ADMIN');const d=await body(c);if(d.app_password?.trim())throw fail(400,'Cloudflare uses Gmail OAuth API. Configure OAuth Worker secrets; Gmail app passwords are not supported.');const enabled=bool(d,'enabled',true),user=enabled?text(d,'user'):d.user??'',fetch_limit=num(d,'fetch_limit',25,true);if(!Number.isInteger(fetch_limit)||fetch_limit>100)throw fail(422,'fetch_limit must be 1 to 100');const value=JSON.stringify({enabled,user,mailbox:text(d,'mailbox','INBOX'),fetch_query:d.fetch_query==='UNSEEN'?'is:unread':text(d,'fetch_query','is:unread'),fetch_limit});await run(c,"INSERT INTO integration_settings(key,value) VALUES('gmail',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",value);return c.json({ok:true,message:'Gmail settings saved. OAuth credentials are managed as Worker secrets.',gmail:await gmailStatus(c)});});
 app.post('/api/settings/gmail/test',async c=>{requireRoles(c,'ADMIN');const token=await gmailToken(c);const profile=await gmailFetch(c,'profile',token);return c.json({ok:true,message:`Gmail connected to ${profile.emailAddress}`,gmail:await gmailStatus(c)});});
 app.post('/api/integrations/gmail/push',async c=>{const payload=await body(c);await insert(c,'audit_logs',{module:'gmail',action:'PUSH_RECEIVED',details:JSON.stringify(payload).slice(0,2000),user_name:'gmail'});return c.json({ok:true});});
 app.post('/api/integrations/gmail/reconcile',async c=>{requireRoles(c,'ADMIN');const settings=await gmailStatus(c),token=await gmailToken(c);const list=await gmailFetch(c,'messages?'+new URLSearchParams({q:settings.fetch_query,labelIds:settings.mailbox,maxResults:String(settings.fetch_limit)}),token);let imported=0,skipped_existing=0;const errors:string[]=[];for(const ref of list.messages??[]){try {const external_id='gmail:'+ref.id;if(await one(c,'SELECT id FROM inbox_messages WHERE external_message_id=?',external_id)){skipped_existing++;continue;}const msg=await gmailFetch(c,`messages/${ref.id}?format=full`,token);const headers=msg.payload?.headers??[],header=(key:string)=>headers.find((h:Data)=>h.name.toLowerCase()===key)?.value??'';const sender=header('from'),email=sender.match(/<([^>]+)>/)?.[1]??sender;const customer=await one(c,'SELECT id FROM customers WHERE lower(email)=?',email.toLowerCase()) as Data|null;const bodyParts:string[]=[];function visit(part:Data){if(part.mimeType==='text/plain'&&part.body?.data){const encoded=part.body.data.replace(/-/g,'+').replace(/_/g,'/');bodyParts.push(new TextDecoder().decode(Uint8Array.from(atob(encoded),x=>x.charCodeAt(0))));}for(const child of part.parts??[])visit(child);}visit(msg.payload??{});await insert(c,'inbox_messages',{source:'gmail',external_message_id:external_id,sender,subject:header('subject')||'(no subject)',body:(bodyParts.join('\n\n')||msg.snippet||'').slice(0,10000),received_at:new Date(Number(msg.internalDate)).toISOString(),archived:false,status:customer?'MATCHED':'RECEIVED',customer_id:customer?.id??null});imported++;}catch{errors.push(`Failed to import message ${ref.id}`);}}return c.json({ok:errors.length===0,fetched:list.messages?.length??0,imported,skipped_existing,errors,message:`Imported ${imported} Gmail message(s), skipped ${skipped_existing}.`});});
}



